In [7]:
import numpy as np  # optional
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.2.0
{'system': {'commit': '3e89b4c4b1580aa890023fc550774e63d499da25', 'python': '3.8.6.final.0', 'python-bits': 32, 'OS': 'Windows', 'OS-release': '10', 'Version': '10.0.19041', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'byteorder': 'little', 'LC_ALL': None, 'LANG': 'en.UTF-8', 'LOCALE': {'language-code': 'English_United States', 'encoding': '1252'}}, 'dependencies': {'pandas': '1.2.0', 'numpy': '1.19.4', 'pytz': '2020.5', 'dateutil': '2.8.1', 'pip': '21.0', 'setuptools': '49.2.1', 'Cython': None, 'pytest': None, 'hypothesis': None, 'sphinx': None, 'blosc': None, 'feather': None, 'xlsxwriter': None, 'lxml.etree': None, 'html5lib': None, 'pymysql': None, 'psycopg2': None, 'jinja2': '2.11.2', 'IPython': '7.19.0', 'pandas_datareader': None, 'bs4': None, 'bottleneck': None, 'fsspec': None, 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.3.4', 'numexpr': None, 'odfpy': None, 'openpyxl': '3.0.5', 'pandas_gbq': None, 'pyarrow': None, 'pyxlsb

     
     2.create a series from a list, numpy array and dict
 

In [10]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

# Solution
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64


3. convert the index of a series into a column of a dataframe


In [13]:
# Input
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

# Solution
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


4.  combine many series to form a dataframe


In [14]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solution 1
df = pd.concat([ser1, ser2], axis=1)

# Solution 2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


5. assign name to the series’ index

In [18]:
# Input
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

# Solution
ser.name = 'alphabets'
ser.head()
    


0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

6. get the items of series A not present in series B

In [20]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

7. get the items not common to both series A and series B

In [21]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solution
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

8. get the minimum, 25th percentile, median, 75th, and max of a numeric series


In [23]:
# Input
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

# Solution
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

9. get frequency counts of unique items of a series

In [24]:
# Input
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

# Solution
ser.value_counts()

c    7
a    6
e    5
h    4
f    3
g    2
d    2
b    1
dtype: int64

In [ ]:
10. keep only top 2 most frequent values as it is and replace everything else as ‘Other’

In [25]:
# Input
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Solution
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

Top 2 Freq: 1    4
3    3
4    3
2    2
dtype: int64


0     Other
1         3
2     Other
3     Other
4         3
5         3
6     Other
7         1
8         1
9         1
10    Other
11        1
dtype: object

11. bin a numeric series to 10 groups of equal size

In [26]:
# Input
ser = pd.Series(np.random.random(20))
print(ser.head())

# Solution
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()




0    0.737128
1    0.057274
2    0.181399
3    0.108913
4    0.694334
dtype: float64


0    9th
1    1st
2    4th
3    2nd
4    8th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

12. convert a numpy array to a dataframe of given shape

In [27]:
# Input
ser = pd.Series(np.random.randint(1, 10, 35))

# Solution
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  6  7  1  4  9
1  9  6  3  5  9
2  9  4  3  7  8
3  4  9  8  8  1
4  7  8  3  7  9
5  9  7  1  6  8
6  2  4  9  9  2



13. find the positions of numbers that are multiples of 3 from a series

In [ ]:
# Input
ser = pd.Series(np.random.randint(1, 10, 7))
ser

# Solution
print(ser)
np.argwhere(ser % 3==0)

0    6
1    8
2    6
3    7
4    6
5    2
6    4
dtype: int64

array([[0],
       [2],
       [4]])

14.  extract items at given positions from a series

In [32]:
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

15. to stack two series vertically and horizontally

In [33]:
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
ser1.append(ser2)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


16.  get the positions of items of series A in another series B

In [34]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

17. compute the mean squared error on a truth and predicted series

In [35]:
# Input
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Solution
np.mean((truth-pred)**2)

0.5164822466180231

18. to convert the first character of each element in a series to uppercase

In [36]:
# Input
ser = pd.Series(['how', 'to', 'lift', 'up?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

19. calculate the number of characters in each word in a series

In [38]:
# Input
ser = pd.Series(['how', 'to', 'lift', 'up?'])

# Solution
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    3
dtype: int64

20. compute difference of differences between consequtive numbers of a series

In [40]:
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

# Solution
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


21.  convert a series of date-strings to a timeseries

In [41]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution 1
from dateutil.parser import parse
ser.map(lambda x: parse(x))

# Solution 2
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

22. get the day of month, week number, day of year and day of week from a series of date strings

In [46]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011',  '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Solution
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.weekofyear.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())



Date:  [1, 2, 4, 5, 6]
Week number:  [53, 5, 14, 19, 23]
Day number of year:  [1, 33, 94, 125, 157]


<ipython-input-46-3ddccf5271b7>:12: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print("Week number: ", ser_ts.dt.weekofyear.tolist())


23.  convert year-month string to dates corresponding to the 4th day of the month

In [47]:
import pandas as pd
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
# Parse the date
ser_ts = ser.map(lambda x: parse(x))

# Construct date string with date as 4
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

# Format it.
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

24.filter words that contain atleast 2 vowels from a series

In [48]:
# Input
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

# Solution
from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

25. filter valid emails from a series

In [51]:
# Input
emails = pd.Series(['buying books at amazom.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['matt@t.co', 'narendra@modi.com']

26. get the mean of a series grouped by another series

In [52]:
# Input
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Solution
weights.groupby(fruit).mean()

apple     6.250000
banana    5.666667
carrot    4.333333
dtype: float64

27.  compute the euclidean distance between two series

In [53]:
# Input
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# Solution 
sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)

18.16590212458495

28.  find all the local maxima (or peaks) in a numeric series

In [54]:
# Input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# Solution
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7], dtype=int32)

29. replace missing spaces in a string with the least frequent character

In [55]:
# Input
my_str = 'dbc deb abed gade'

# Solution
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
e    3
b    3
     3
a    2
c    1
g    1
dtype: int64


'dbcgdebgabedggade'

30. create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values

In [56]:
# Solution
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    7
2000-01-08    7
2000-01-15    2
2000-01-22    4
2000-01-29    1
2000-02-05    2
2000-02-12    9
2000-02-19    3
2000-02-26    3
2000-03-04    6
Freq: W-SAT, dtype: int32

31. fill an intermittent time series so all missing dates show up with values of previous non-missing date

In [57]:
# Input
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

# Solution
ser.resample('D').ffill()  # fill with previous value

# Alternatives
ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

32.  create a dataframe with rows as strides from a given series

In [60]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

33.  change the order of columns of a dataframe



In [61]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)

34.format or suppress scientific notations in a pandas dataframe

In [62]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)

# Solution 2: Use apply to change format
df.apply(lambda x: '%.4f' % x, axis=1)
# or
df.applymap(lambda x: '%.4f' % x)

# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0000
1  0.0054
2  0.0002
3  0.0000


35. get the row number of the nth largest value in a column

In [65]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

9

36.   reshape a dataframe to the largest possible square after removing the negative values

In [73]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  17  21   0 -20  39   2  -2  46  27  24
1 -10  33   3  -8 -14  26  10  19 -20 -20
2  21 -13  36  49  41  44  29  10  40 -11
3  18   5  21  29 -11   8  41  -2  47  41
4  21  39   0   3  22  38  46   4  11  49
5   1  -7  32  44  22  26  11  36  12  40
6 -13  11   4  11  10  25 -13  18  -4  44
7  23  10  48  43 -20  25  17 -14 -12  35
8 -19  44  34  43  27  40   0   7  20  10
9 -12  44  30  -7  30 -20   9  10  17  15
[[17. 21. 39. 46. 27. 24. 33. 26.]
 [10. 19. 21. 36. 49. 41. 44. 29.]
 [10. 40. 18. 21. 29. 41. 47. 41.]
 [21. 39. 22. 38. 46. 11. 49. 32.]
 [44. 22. 26. 11. 36. 12. 40. 11.]
 [11. 25. 18. 44. 23. 10. 48. 43.]
 [25. 17. 35. 44. 34. 43. 27. 40.]
 [20. 10. 44. 30. 30. 10. 17. 15.]]


37. reverse the rows of a dataframe

In [74]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


38. normalize all columns in a dataframe

In [75]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0  0.53  1.33 -1.71 -0.92  1.32  1.16 -0.82  1.59  0.11  0.05
1  1.83 -0.86  0.15 -1.01 -1.20  0.73 -0.46 -0.47 -1.11 -0.72
2 -0.70  0.16  0.97  0.19  1.12  0.39  0.62  0.37 -0.51 -0.94
3 -1.18  1.22  0.65 -0.15  0.44 -0.01 -0.73 -1.12  1.43  1.16
4  0.12 -0.22  0.04  1.34 -0.52 -1.11 -0.37 -0.31 -0.20 -1.46
5  0.01 -1.58  1.30 -0.67 -0.35 -0.62  2.06 -1.22 -0.67  1.13
6  0.49 -0.48 -0.74 -0.41 -1.31 -1.54  0.48  1.12  1.59  0.91
7 -1.11  0.43 -0.67  1.64  0.50  0.99 -0.78  0.03 -0.64 -0.13
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.43  0.00  1.00  0.97  0.00  0.00  1.00  0.00  0.55  0.42
1  0.00  0.75  0.38  1.00  0.96  0.16  0.88  0.73  1.00  0.72
2  0.84  0.40  0.11  0.55  0.08  0.29  0.50  0.43  0.78  0.80
3  1.00  0.04  0.21  0.68  0.33  0.44  0.97  0.97  0.06  0.00
4  0.57  0.53  0.42  0.11  0.70  0.84  0.84  0.68  0.66  1.00
5  0.60  1.00  0.00  0.87  0.63  0.66  0.00 